# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d23a1cdfac2cb94b4b1d23086fbd4d9460f50ea044d4754f40afdc9f02b197f8ec425efd4250fc3723d27ad18b111e8d101b81727203789d239de3598724d0e4

test:
  secret_key_base: 59b7265e425b3c2b0300f25514981e4e6c6fa79597f4e58aa6e3914ddf6d8e41e902cfcfc8c816f1402437e441920c67cf8dff842da98549f81eb34a9292f9eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
